import Head from "next/head";
import { useContext } from "react";
import { Button } from "antd";

import { WalletContext } from "@/context/WalletContext";
import { SUPPORTED_NETWORKS } from "@/constants/network";
export default function Home() {
  const {
    account,
    currentNetwork,
    connectionStatus,
    tokenBalances,
    connectWallet,
    switchNetwork,
    getTokenBalances,
  } = useContext(WalletContext);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        {account && <p>{account}</p>}
        <Button onClick={connectWallet}>Connect Wallet</Button>
        <div>
          {SUPPORTED_NETWORKS.map((network) => (
            <Button
              type={currentNetwork?.id === network.id ? "primary" : "default"}
              key={network.id}
              onClick={() => switchNetwork(network.id)}
              disabled={connectionStatus === "connecting"}
            >
              {network.name}
            </Button>
          ))}
        </div>
        {!tokenBalances.length && (
          <Button onClick={getTokenBalances}>Get Balances</Button>
        )}
        {tokenBalances.length > 0 && (
          <div>
            {tokenBalances.map((balance) => (
              <p key={balance.token.symbol}>{balance.formattedBalance}</p>
            ))}
          </div>
        )}
      </main>
      <footer></footer>
    </>
  );
}
